clear
close all;

addpath(genpath("sub_functions"))
addpath("func_metrics")
addpath("./methods/real")

fprintf("******* initium *******\n");

%% Selecting conditions
images = {...
    "IndianPines", ...
    "Suwannee", ...
};

% idc_images = 1:numel(images);
idc_images = 2;


idx_exp = 0;
total_exp = length(idc_images);


%% Setting common parameters
% IndianPines
% epsilon = 30;
% alpha = 200;
% beta = 100;

%Suwannee
epsilon = 100;
alpha = 800;
beta = 5000;

stopcri_idx = 5;
stopcri = 10 ^ -stopcri_idx;

maxiter = 20000;
% maxiter = 5;


%% Setting each methods info
% GeoSSTV
GeoSSTV.lambda = {0.001, 0.005, 0.01, 0.03};

methods_info(1) = struct( ...
    "name", "GeoSSTV", ...
    "func", @(HSI_noisy, params) ...
        func_GeoSSTV_real_for_denoising(HSI_noisy, params), ...
    "param_names", {{"lambda", "maxiter", "stopcri", "epsilon", "alpha", "beta"}}, ...
    "params", {{GeoSSTV.lambda, maxiter, stopcri, epsilon, alpha, beta}}, ...
    "get_params_savetext", @(params) ...
        sprintf("e%g_a%g_b%g_o%g_stop1e-%d", ...
        params.epsilon, params.alpha, params.beta, params.lambda, stopcri_idx), ...
    "enable", true ...
);

% SSTV
methods_info(end+1) = struct( ...
    "name", "SSTV", ...
    "func", @(HSI_noisy, params) ...
        func_SSTV_real_for_denoising(HSI_noisy, params), ...
    "param_names", {{"maxiter", "stopcri", "epsilon", "alpha", "beta"}}, ...
    "params", {{maxiter, stopcri, epsilon, alpha, beta}}, ...
    "get_params_savetext", @(params) ...
        sprintf("e%g_a%g_b%g_stop1e-%d", params.epsilon, params.alpha, params.beta, stopcri_idx), ...
    "enable", false ...
);

% HSSTV_L1
% HSSTV.omega = {0.05};
HSSTV.omega = {0.03, 0.05, 0.07};

methods_info(end+1) = struct( ...
    "name", "HSSTV_L1", ...
    "func", @(HSI_noisy, params) ...
        func_HSSTV_real_for_denoising(HSI_noisy, params), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "epsilon", "alpha", "beta"}}, ...
    "params", {{{"L1"}, HSSTV.omega, maxiter, stopcri, epsilon, alpha, beta}}, ...
    "get_params_savetext", @(params) ...
        sprintf("e%g_a%g_b%g_o%.2f_stop1e-%d", ...
        params.epsilon, params.alpha, params.beta, params.omega, stopcri_idx), ...
    "enable", true ...
);

% HSSTV_L12
methods_info(end+1) = struct( ...
    "name", "HSSTV_L12", ...
    "func", @(HSI_noisy, params) ...
        func_HSSTV_real_for_denoising(HSI_noisy, params), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "epsilon", "alpha", "beta"}}, ...
    "params", {{{"L12"}, HSSTV.omega, maxiter, stopcri, epsilon, alpha, beta}}, ...
    "get_params_savetext", @(params) ...
        sprintf("e%g_a%g_b%g_o%.2f_stop1e-%d", ...
        params.epsilon, params.alpha, params.beta, params.omega, stopcri_idx), ...
    "enable", true ...
);

% l0l1HTV
% l0l1HTV_stepsize_reduction = {0.999, 0.9999};
l0l1HTV_stepsize_reduction = {0.999};
% l0l1HTV_stepsize_reduction = 1;

l0l1HTV_L10ball_th = {0.02, 0.03};


methods_info(end+1) = struct( ...
    "name", "l0l1HTV", ...
    "func", @(HSI_noisy, params)...
        func_l0l1HTV_real_for_denoising(HSI_noisy, params), ...
    "param_names", {{"L10ball_th", "stepsize_reduction", ...
        "maxiter", "stopcri", "epsilon", "alpha", "beta"}}, ...
"params", {{l0l1HTV_L10ball_th, l0l1HTV_stepsize_reduction, ...
        maxiter, stopcri, epsilon, alpha, beta}}, ...
    "get_params_savetext", @(params) ...
        sprintf("e%g_a%g_b%g_sr%.5g_th%.2f_maxiter%d", ...
            params.epsilon, params.alpha, params.beta, ...
            params.stepsize_reduction, params.L10ball_th, maxiter), ...
    "enable", true ...
);

% LRTDTV
LRTDTV_tau = 1;
% LRTDTV_lambda = 100;
% LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(hsi.n1*hsi.n2)};
% LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(hsi.n1*hsi.n2), LRTDTV_lambda_param);
LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(100*100)};
LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(100*100), LRTDTV_lambda_param);
% LRTDTV_rank = {[51,51,10]};
% LRTDTV_rank = {[hsi.n1*0.8, hsi.n2*0.8, 10], [51, 51, 10]};
LRTDTV_rank = {[100*0.8, 100*0.8, 10], [51, 51, 10]};

methods_info(end+1) = struct( ...
    "name", "LRTDTV", ...
    "func", @(HSI_noisy, params) ...
        func_LRTDTV(HSI_noisy, params), ...
    "param_names", {{"tau", "lambda", "rank"}}, ...
    "params", {{LRTDTV_tau, LRTDTV_lambda, LRTDTV_rank}}, ...
    "get_params_savetext", @(params) ...
        sprintf("l%.4g_r%d_stop1e-%d", params.lambda, params.rank(1), stopcri_idx), ...
    "enable", false ...
);

% TPTV
TPTV.Rank = {[7,7,5]};
TPTV.initial_rank = {2};
TPTV.maxIter = {50, 100};
% TPTV.lambda = 4e-3*sqrt(hsi.n1*hsi.n2);
TPTV.lambdas = {5e-4, 1e-4, 1e-3, 1e-2, 1.5e-2};

methods_info(end+1) = struct( ...
    "name", "TPTV", ...
    "func", @(HSI_noisy, params) ...
        func_TPTV_for_denoising(HSI_noisy, params), ...
    "param_names", {{"Rank", "initial_rank", "maxIter", "lambda"}}, ...
    "params", {{TPTV.Rank, TPTV.initial_rank, TPTV.maxIter, TPTV.lambdas}}, ...
    "get_params_savetext", @(params) ...
        sprintf("maxiter%d_l%.4g", params.maxIter, params.lambda), ...
    "enable", false ...
);

% FastHyMix
FastHyMix_k_subspace = {4, 8, 12};
methods_info(end+1) = struct( ...
    "name", "FastHyMix", ...
    "func", @(HSI_noisy, params) ...
        func_FastHyMix(HSI_noisy, params), ...
    "param_names", {{"k_subspace"}}, ...
    "params", {{FastHyMix_k_subspace}}, ...
    "get_params_savetext", @(params) ...
        sprintf("sub%d", params.k_subspace), ...
    "enable", false ...
);


methods_info = methods_info([methods_info.enable]); % removing false methods
num_methods = numel(methods_info);


%% Running Expt.
for idx_image = idc_images
%% Generating observation
image = images{idx_image};

[HSI_noisy, hsi] = Load_real_HSI(image);
HSI_noisy = single(HSI_noisy);


idx_exp = idx_exp + 1;

i_method = 0;


%% Running methods
for idx_method = 1:num_methods
name_method = methods_info(idx_method).name;
func_method = methods_info(idx_method).func;
params_name = methods_info(idx_method).param_names;
params_cell = methods_info(idx_method).params;


i_method = i_method + 1;


[params_comb, num_params_comb] = ParamsList2Comb(params_cell);

for idx_params_comb = 1:num_params_comb

params = struct();
for idx_params = 1:numel(params_name)
    % Assigning parameters to the structure
    params.(params_name{idx_params}) = params_comb{idx_params_comb}{idx_params};
end

name_params_savetext = methods_info(idx_method).get_params_savetext(params);


fprintf("\n~~~ SETTINGS ~~~\n");
fprintf("Method: %s\n", name_method);
fprintf("Image: %s Size: (%d, %d, %d)\n", image, hsi.n1, hsi.n2, hsi.n3);
fprintf("Parameter settings: %s\n", name_params_savetext)
fprintf("Methods: (%d/%d), Cases: (%d/%d), Params:(%d/%d)\n", ...
    i_method, num_methods, idx_exp, total_exp, idx_params_comb, num_params_comb);

[HSI_restored, removed_noise, other_result]...
    = func_method(HSI_noisy, params);


% Saving each result
load("dir_save_folder.mat", "dir_save_folder");
load("dir_save_comp_folder.mat", "dir_save_comp_folder")

dir_save_method_folder = fullfile(...
    dir_save_folder, ...
    append("denoising_", image), ...
    name_method ...
);

dir_save_comp_method_folder = fullfile(...
    dir_save_comp_folder, ...
    append("denoising_", image), ...
    name_method ...
);

mkdir(dir_save_method_folder);
mkdir(dir_save_comp_method_folder);

save(fullfile(dir_save_method_folder, append(name_params_savetext, ".mat")), ...
    "HSI_noisy", "hsi", "image", ...
    "HSI_restored", "removed_noise", ...
    "params", "other_result", ...
    "-v7.3", "-nocompression" ...
);
save(fullfile(dir_save_comp_method_folder, append(name_params_savetext, ".mat")), ...
    "HSI_restored", "params", ...
    "-v7.3", "-nocompression" ...
);

close all

end

end
end

fprintf("******* finis *******\n");
