clear
close all;

addpath(genpath("sub_functions"))
addpath("func_metrics")
addpath("methods")

fprintf("******* initium *******\n");

%% Selecting conditions
% noise_conditions = { ...
%     %g      ps     pt     t_int pd
%     {0.05,  0.05,  0.05,  0.5,  0.01}, ... % g0.05 ps0.05 pt0.05 pd0.001
%     {0.1,   0.05,  0.05,  0.5,  0.01}, ... % g0.1 ps0.05 pt0.05 pd0.001
%     {0.05,  0.05,  0.05,  0.5,  0.03}, ... % g0.1 ps0.05 pt0.05 pd0.001
%     {0.1,   0.05,  0.05,  0.5,  0.03}, ... % g0.1 ps0.05 pt0.05 pd0.001
%     {0.05,  0.05,  0,     0,    0   }, ...
%     {0.1,   0.05,  0,     0,    0   }, ...
%     {0.05,  0.05,  0.05,  0.5,  0   }, ...
%     {0.1,   0.05,  0.05,  0.5,  0   }, ...
%     {0.2,   0.05,  0,     0,    0   }, ...
%     {0.2,   0.05,  0.05,  0.5,  0   }, ...
% };

noise_conditions = { ...
    %g      ps     pt     t_int pd
    {0.1,   0,     0,     0,    0   }, ...
    {0.1,   0.05,  0,     0,    0   }, ...
    {0.1,   0,     0.05,  0.5,  0   }, ...
    {0.1,   0,     0,     0,    0.01}, ...
    {0.1,   0.05,  0.05,  0.5,  0.01}, ...
    {0.2,   0.05,  0.05,  0.5,  0.01}, ...
    };

% idc_noise_conditions = 1:size(noise_conditions, 2);
idc_noise_conditions = 6;


images = {...
    "JasperRidge", ...
    "PaviaU", ...
    };

% images = {...
%     "JasperRidge64", ...
%     "PaviaU64", ...
% };

% is_flipped = {...
%     0, ...
%     1, ...
%     0, ...
%     1, ...
% };

idc_images = 1:numel(images);
% idc_images = 1;


idx_exp = 0;
total_exp = length(idc_noise_conditions) * length(idc_images);


%% Setting common parameters
% rhos = {0.93, 0.95, 0.98};
rhos = {0.90};
% rhos = {0.98};

% epsilon_rho = 0.01;

% % epsilon = epsilon_rho * sqrt(hsi.N * (1 - deg.sparse_rate));
% epsilon = rhos * deg.gaussian_sigma * sqrt(hsi.N * (1 - deg.sparse_rate));
% alpha = rhos * (0.5 * hsi.N * deg.sparse_rate);
% beta = rhos * hsi.N * (1 - deg.sparse_rate) ...
%     * deg.stripe_rate * deg.stripe_intensity / 2;

stopcri_idx = 5;
stopcri = 10 ^ -stopcri_idx;

maxiter = 20000;
% maxiter = 5;

load("dir_save_folder.mat", "dir_save_folder");
load("dir_save_comp_folder.mat", "dir_save_comp_folder")


%% Setting each methods info
% GeoSSTV
% GeoSSTV.lambda = {0.001, 0.005, 0.01, 0.03};
% GeoSSTV.lambda = {0.01, 0.02, 0.03, 0.05};
GeoSSTV.lambda = {0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07};

methods_info(1) = struct( ...
    "name", "GeoSSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    select_func_GeoSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"lambda", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{GeoSSTV.lambda, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
    sprintf("o%g_r%.2f_stop1e-%d", params.lambda, params.rho_radius, stopcri_idx), ...
    "enable", true ...
    );

% SSTV
methods_info(end+1) = struct( ...
    "name", "SSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    select_func_SSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
    sprintf("r%.2f_stop1e-%d", params.rho_radius, stopcri_idx), ...
    "enable", false ...
    );

% HSSTV_L1
% HSSTV.omega = {0.05};
HSSTV.omega = {0.03, 0.05, 0.07};

methods_info(end+1) = struct( ...
    "name", "HSSTV_L1", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    select_func_HSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, HSSTV.omega, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
    sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, params.rho_radius, stopcri_idx), ...
    "enable", false ...
    );

% HSSTV_L12
methods_info(end+1) = struct( ...
    "name", "HSSTV_L12", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    select_func_HSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L12"}, HSSTV.omega, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
    sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, params.rho_radius, stopcri_idx), ...
    "enable", false ...
    );

% l0l1HTV
l0l1HTV_stepsize_reduction = {0.999, 0.9999};
% l0l1HTV_stepsize_reduction = 0.9999;
% l0l1HTV_stepsize_reduction = 1;

l0l1HTV_L10ball_th = {0.02, 0.03};


methods_info(end+1) = struct( ...
    "name", "l0l1HTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg)...
    select_func_l0l1HTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L10ball_th", "stepsize_reduction", ...
    "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{l0l1HTV_L10ball_th, l0l1HTV_stepsize_reduction, ...
    maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
    sprintf("sr%.5g_th%.2f_r%.2f_maxiter%d", ...
    params.stepsize_reduction, params.L10ball_th, params.rho_radius, maxiter), ...
    "enable", false ...
    );

% LRTDTV
LRTDTV_tau = 1;
% LRTDTV_lambda = 100;
% LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(hsi.n1*hsi.n2)};
% LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(hsi.n1*hsi.n2), LRTDTV_lambda_param);
LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(100*100)};
LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(100*100), LRTDTV_lambda_param);
% LRTDTV_rank = {[51,51,10]};
% LRTDTV_rank = {[hsi.n1*0.8, hsi.n2*0.8, 10], [51, 51, 10]};
LRTDTV_rank = {[100*0.8, 100*0.8, 10], [51, 51, 10]};

methods_info(end+1) = struct( ...
    "name", "LRTDTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    func_LRTDTV(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"tau", "lambda", "rank"}}, ...
    "params", {{LRTDTV_tau, LRTDTV_lambda, LRTDTV_rank}}, ...
    "get_params_savetext", @(params) ...
    sprintf("l%.4g_r%d_stop1e-%d", params.lambda, params.rank(1), stopcri_idx), ...
    "enable", false ...
    );

% TPTV
TPTV.Rank = {[7,7,5]};
TPTV.initial_rank = {2};
TPTV.maxIter = {50, 100};
% TPTV_lambda = 4e-3*sqrt(hsi.n1*hsi.n2);
% TPTV.lambdas = {5e-4, 1e-4, 1e-3, 1e-2, 1.5e-2, 4e-3*sqrt(100*100)};
TPTV.lambdas = {5e-4, 1e-4, 1e-3, 1e-2, 1.5e-2};

methods_info(end+1) = struct( ...
    "name", "TPTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    func_TPTV(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"Rank", "initial_rank", "maxIter", "lambda"}}, ...
    "params", {{TPTV.Rank, TPTV.initial_rank, TPTV.maxIter, TPTV.lambdas}}, ...
    "get_params_savetext", @(params) ...
    sprintf("maxiter%d_l%.4g", params.maxIter, params.lambda), ...
    "enable", false ...
    );

% FastHyMix
FastHyMix_k_subspace = {4, 8, 12};
methods_info(end+1) = struct( ...
    "name", "FastHyMix", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
    func_FastHyMix(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"k_subspace"}}, ...
    "params", {{FastHyMix_k_subspace}}, ...
    "get_params_savetext", @(params) ...
    sprintf("sub%d", params.k_subspace), ...
    "enable", false ...
    );


methods_info = methods_info([methods_info.enable]); % removing false methods
num_methods = numel(methods_info);


%% Running Expt.
for idx_noise_condition = idc_noise_conditions
    for idx_image = idc_images
        %% Generating observation
        deg.gaussian_sigma      = noise_conditions{idx_noise_condition}{1};
        deg.sparse_rate         = noise_conditions{idx_noise_condition}{2};
        deg.stripe_rate         = noise_conditions{idx_noise_condition}{3};
        deg.stripe_intensity    = noise_conditions{idx_noise_condition}{4};
        deg.deadline_rate       = noise_conditions{idx_noise_condition}{5};
        image = images{idx_image};

        [HSI_clean, hsi] = Load_HSI(image);
        noise_seed = "default";
        [HSI_noisy, deg] = Generate_obsv_for_denoising(HSI_clean, deg, noise_seed);

        HSI_clean = single(HSI_clean);
        HSI_noisy = single(HSI_noisy);


        % if is_flipped{idx_image}
        %     HSI_clean = flip(HSI_clean, 2);
        %     HSI_noisy = flip(HSI_noisy, 2);
        %     image = image + "f";
        % end


        idx_exp = idx_exp + 1;

        i_method = 0;


        %% Running methods
        for idx_method = 1:num_methods
            name_method = methods_info(idx_method).name;
            func_method = methods_info(idx_method).func;
            params_name = methods_info(idx_method).param_names;
            params_cell = methods_info(idx_method).params;


            i_method = i_method + 1;


            [params_comb, num_params_comb] = ParamsList2Comb(params_cell);

            for idx_params_comb = 1:num_params_comb

                params = struct();
                for idx_params = 1:numel(params_name)
                    % Assigning parameters to the structure
                    params.(params_name{idx_params}) = params_comb{idx_params_comb}{idx_params};

                    % If rho_radius exists, calculate epsilon, alpha, and beta
                    if strcmp(params_name{idx_params}, "rho_radius")
                        % Calculating the rate except sparse noise and deadline noise
                        r_sp = deg.sparse_rate;
                        r_dl = deg.deadline_rate;
                        dl_mean_width = 2;
                        cr_dl = 1 - exp(-dl_mean_width * r_dl); % cover_rate of deadline

                        mask_valid = (HSI_noisy > 0) & (HSI_noisy < 1);
                        mu = mean(HSI_noisy(mask_valid), 'all');

                        params.epsilon = params.rho_radius * deg.gaussian_sigma * sqrt(hsi.N * (1 - r_sp) * (1 - cr_dl));
                        params.alpha = params.rho_radius * hsi.N * (0.5*r_sp + mu*cr_dl);
                        params.beta    = params.rho_radius * hsi.N * (1 - r_sp) * (1 - cr_dl) ...
                            * (deg.stripe_rate * deg.stripe_intensity / 2);
                    end
                end

                name_params_savetext = methods_info(idx_method).get_params_savetext(params);


                fprintf("\n~~~ SETTINGS ~~~\n");
                fprintf("Method: %s\n", name_method);
                fprintf("Image: %s Size: (%d, %d, %d)\n", image, hsi.n1, hsi.n2, hsi.n3);
                fprintf("Gaussian sigma: %g\n", deg.gaussian_sigma);
                fprintf("Sparse rate: %g\n", deg.sparse_rate);
                fprintf("Stripe rate: %g\n", deg.stripe_rate);
                fprintf("Stripe intensity: %g\n", deg.stripe_intensity);
                fprintf("Deadline rate: %g\n", deg.deadline_rate);
                fprintf("Parameter settings: %s\n", name_params_savetext)
                fprintf("Methods: (%d/%d), Cases: (%d/%d), Params:(%d/%d)\n", ...
                    i_method, num_methods, idx_exp, total_exp, idx_params_comb, num_params_comb);

                [HSI_restored, removed_noise, other_result]...
                    = func_method(HSI_clean, HSI_noisy, params, deg);


                % Plotting results
                val_mpsnr  = calc_MPSNR(HSI_restored, HSI_clean);
                val_mssim  = calc_MSSIM(HSI_restored, HSI_clean);
                val_sam    = calc_SAM(HSI_restored, HSI_clean);

                fprintf("~~~ RESULTS ~~~\n");
                fprintf("MPSNR: %#.4g\n", val_mpsnr);
                fprintf("MSSIM: %#.4g\n", val_mssim);
                fprintf("SAM  : %#.4g\n", val_sam);

                [vals_psnr_per_band, vals_ssim_per_band] = calc_PSNR_SSIM_per_band(HSI_restored, HSI_clean);


                % Saving each result
                dir_save_method_folder = fullfile(...
                    dir_save_folder, ...
                    append("denoising_", image), ...
                    append("g", num2str(deg.gaussian_sigma), "_ps", num2str(deg.sparse_rate), ...
                    "_pt", num2str(deg.stripe_rate), "_pd", num2str(deg.deadline_rate)), ...
                    name_method ...
                    );

                dir_save_comp_method_folder = fullfile(...
                    dir_save_comp_folder, ...
                    append("denoising_", image), ...
                    append("g", num2str(deg.gaussian_sigma), "_ps", num2str(deg.sparse_rate), ...
                    "_pt", num2str(deg.stripe_rate), "_pd", num2str(deg.deadline_rate)), ...
                    name_method ...
                    );

                mkdir(dir_save_method_folder);
                mkdir(dir_save_comp_method_folder);

                save(fullfile(dir_save_method_folder, append(name_params_savetext, ".mat")), ...
                    "HSI_clean", "HSI_noisy", "hsi", "deg", "image", ...
                    "HSI_restored", "removed_noise", ...
                    "val_mpsnr", "val_mssim", "val_sam", ...
                    "vals_psnr_per_band", "vals_ssim_per_band", ...
                    "params", "other_result", ...
                    "-v7.3", "-nocompression" ...
                    );
                save(fullfile(dir_save_comp_method_folder, append(name_params_savetext, ".mat")), ...
                    "HSI_restored", "params", "val_mpsnr", "val_mssim", "val_sam", ...
                    "-v7.3", "-nocompression" ...
                    );

                close all

            end

        end
    end
end

fprintf("******* finis *******\n");
